services:
  backendservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - '8085:80'
    volumes:
      # For UserSecrets (macOS/Linux path)
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      # For HTTPS dev certificates (macOS/Linux path)
      - ~/.aspnet/https:/root/.aspnet/https:ro
