services:
  backendservice:
    container_name: 'backendservice'
    image: ${DOCKER_REGISTRY-}backendservice
    volumes:
      - /private/tmp:/tmp
    env_file:
      - .env
    build:
      context: ../backend/backendService
      dockerfile: Dockerfile
    ports:
      - '8085:80'

  webclient:
    container_name: 'landseawebclient'
    image: ${DOCKER_REGISTRY-}landseawebclient
    build:
      context: ../recruitmentsite
      dockerfile: Dockerfile
    ports:
      - '8087:8087'
    environment:
      - NODE_ENV=production
